import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk
import cv2
import numpy as np
import pandas as pd
import torch
from facenet_pytorch import MTCNN, InceptionResnetV1
from scipy.spatial.distance import cosine
from datetime import datetime
import os
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ================= EMAIL CONFIG =================
EMAIL_SENDER = "sriyabommakanti@gmail.com"
EMAIL_PASSWORD = "kyka jddt vqiz nnux"   # ⚠️ NEVER PUSH REAL PASSWORD
# ===============================================

ALERT_COOLDOWN_SECONDS = 30
last_alert_times = {}  # child_id -> datetime

# ================= SYSTEM CONFIG =================
META_CSV = "data/cleaned/metadata_private.csv"
LOG_FILE = "data/logs/last_seen.csv"
MATCH_THRESHOLD = 0.75
CAMERA_INDEX = 0
# ===============================================

device = "cuda" if torch.cuda.is_available() else "cpu"

# ================= MODELS =================
mtcnn = MTCNN(keep_all=True, device=device)
resnet = InceptionResnetV1(pretrained="vggface2").eval().to(device)

# ================= LOAD DATABASE =================
df = pd.read_csv(META_CSV)
db_embeddings = []
db_records = []

for _, row in df.iterrows():
    if isinstance(row.get("embedding_path"), str):
        db_embeddings.append(np.load(row["embedding_path"]))
        db_records.append(row)

# ================= UTILITIES =================

def get_current_location():
    try:
        r = requests.get("https://ipinfo.io/json", timeout=5)
        data = r.json()

        city = data.get("city", "Unknown")
        region = data.get("region", "Unknown")
        country = data.get("country", "Unknown")

        loc = data.get("loc", None)  # "lat,lon"

        if loc:
            latitude, longitude = loc.split(",")
        else:
            latitude, longitude = "Unknown", "Unknown"

        return city, region, country, latitude, longitude

    except:
        return "Unknown", "Unknown", "Unknown", "Unknown", "Unknown"


def popup_alert(record, match_pct):
    messagebox.showwarning(
        "🚨 MATCH FOUND",
        f"Name: {record['child_name']}\n"
        f"Match: {match_pct:.2f}%\n"
        f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )


def send_email_alert(record, match_pct):

    city, region, country, latitude, longitude = get_current_location()

    google_maps_link = f"https://www.google.com/maps?q={latitude},{longitude}"

    receivers = []

    if pd.notna(record.get("parent_email")):
        receivers.append(record["parent_email"])

    if pd.notna(record.get("police_email")):
        receivers.append(record["police_email"])

    if not receivers:
        print("⚠️ No email recipients found")
        return

    subject = f"🚨 URGENT: Face Match Detected for {record['child_name']}"

    body = f"""
SAFE SIGHT NOTIFY — EMERGENCY ALERT
------------------------------------------------------

MATCH STATUS: POSITIVE IDENTIFICATION

Child Name: {record['child_name']}
Match Confidence: {match_pct:.2f}%

Detection Timestamp:
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

------------------------------------------------------
DETECTION LOCATION DETAILS
------------------------------------------------------

City: {city}
Region: {region}
Country: {country}

Latitude: {latitude}
Longitude: {longitude}

Google Maps Navigation Link:
{google_maps_link}

------------------------------------------------------
Registered Parent Email: {record.get('parent_email', 'N/A')}
Registered Police Email: {record.get('police_email', 'N/A')}

------------------------------------------------------
This is an automated alert generated by SafeSightNotify.
Immediate verification is recommended.
"""

    msg = MIMEMultipart()
    msg["From"] = EMAIL_SENDER
    msg["To"] = ", ".join(receivers)
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, receivers, msg.as_string())
        server.quit()
        print(f"📧 Alert sent to {receivers}")

    except Exception as e:
        print("❌ Email failed:", e)


def log_last_seen(record, match_pct):
    os.makedirs("data/logs", exist_ok=True)

    pd.DataFrame([{
        "child_id": record["child_id"],
        "child_name": record["child_name"],
        "match_percentage": round(match_pct, 2),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "source": "CAMERA"
    }]).to_csv(LOG_FILE, mode="a", header=not os.path.exists(LOG_FILE), index=False)


def match_embedding(query_emb):
    matches = []
    for db_emb, record in zip(db_embeddings, db_records):
        score = 1 - cosine(query_emb, db_emb)
        if score >= MATCH_THRESHOLD:
            matches.append((score, record))
    return sorted(matches, key=lambda x: x[0], reverse=True)

# ================= LIVE CAMERA =================

def start_camera():
    cap = cv2.VideoCapture(CAMERA_INDEX, cv2.CAP_DSHOW)

    COLORS = [
        (0, 255, 0), (255, 0, 0), (0, 0, 255),
        (255, 255, 0), (255, 0, 255), (0, 255, 255)
    ]

    def update_frame():
        ret, frame = cap.read()
        if not ret:
            return

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        boxes, _ = mtcnn.detect(rgb)
        faces = mtcnn(rgb)

        output_box.delete("1.0", tk.END)

        if faces is not None and boxes is not None:
            for i, face in enumerate(faces):

                color = COLORS[i % len(COLORS)]

                with torch.no_grad():
                    emb = resnet(face.unsqueeze(0).to(device)).cpu().numpy().flatten()

                matches = match_embedding(emb)
                if not matches:
                    continue

                top_score, top_record = matches[0]
                child_id = top_record["child_id"]

                x1, y1, x2, y2 = map(int, boxes[i])
                cv2.rectangle(frame, (x1, y1), (x2, y2), color, 3)

                label = f"{top_record['child_name']} ({top_score*100:.1f}%)"
                cv2.putText(
                    frame,
                    label,
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.7,
                    color,
                    2
                )

                output_box.insert(
                    tk.END,
                    f"Name: {top_record['child_name']}\n"
                    f"Age: {top_record['age']}\n"
                    f"Gender: {top_record['gender']}\n"
                    f"City: {top_record['missing_city']}\n"
                    f"Match: {top_score*100:.2f}%\n"
                    "----------------------------------\n"
                )

                now = datetime.now()
                last_time = last_alert_times.get(child_id)

                if last_time is None or (now - last_time).seconds > ALERT_COOLDOWN_SECONDS:
                    popup_alert(top_record, top_score * 100)
                    send_email_alert(top_record, top_score * 100)
                    log_last_seen(top_record, top_score * 100)
                    last_alert_times[child_id] = now

        img = ImageTk.PhotoImage(
            Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)).resize((640, 480))
        )
        cam_label.configure(image=img)
        cam_label.image = img

        root.after(30, update_frame)

    update_frame()

# ================= GUI =================

root = tk.Tk()
root.title("SafeSightNotify — Multi-Face Alert System")
root.geometry("900x800")

tk.Label(root, text="SafeSightNotify", font=("Arial", 22, "bold")).pack(pady=10)

cam_label = tk.Label(root)
cam_label.pack()

tk.Button(root, text="Start Live Camera", width=30, command=start_camera).pack(pady=10)

output_box = tk.Text(root, height=12, width=100)
output_box.pack(pady=10)

root.mainloop()



# import tkinter as tk
# from tkinter import messagebox
# from PIL import Image, ImageTk
# import cv2
# import numpy as np
# import pandas as pd
# import torch
# from facenet_pytorch import MTCNN, InceptionResnetV1
# from scipy.spatial.distance import cosine
# from datetime import datetime
# import os
# import requests
# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart

# # ================= EMAIL CONFIG =================
# EMAIL_SENDER = "sriyabommakanti@gmail.com"
# EMAIL_PASSWORD = "kyka jddt vqiz nnux"
# # ===============================================

# ALERT_COOLDOWN_SECONDS = 30
# last_alert_times = {}  # child_id -> datetime

# # ================= SYSTEM CONFIG =================
# META_CSV = "data/cleaned/metadata_private.csv"
# LOG_FILE = "data/logs/last_seen.csv"
# MATCH_THRESHOLD = 0.75
# CAMERA_INDEX = 0
# # ===============================================

# device = "cuda" if torch.cuda.is_available() else "cpu"

# # ================= MODELS =================
# mtcnn = MTCNN(keep_all=True, device=device)  # 🔑 MULTI-FACE
# resnet = InceptionResnetV1(pretrained="vggface2").eval().to(device)

# # ================= LOAD DATABASE =================
# df = pd.read_csv(META_CSV)
# db_embeddings = []
# db_records = []

# for _, row in df.iterrows():
#     if isinstance(row.get("embedding_path"), str):
#         db_embeddings.append(np.load(row["embedding_path"]))
#         db_records.append(row)

# # ================= UTILITIES =================

# def get_current_location():
#     try:
#         r = requests.get("https://ipinfo.io/json", timeout=5)
#         d = r.json()
#         return d.get("city", "Unknown"), d.get("region", "Unknown"), d.get("country", "Unknown")
#     except:
#         return "Unknown", "Unknown", "Unknown"

# def popup_alert(record, match_pct):
#     messagebox.showwarning(
#         "🚨 MATCH FOUND",
#         f"Name: {record['child_name']}\n"
#         f"Match: {match_pct:.2f}%\n"
#         f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
#     )

# def send_email_alert(record, match_pct):
#     city, region, country = get_current_location()

#     receivers = []
#     if pd.notna(record.get("parent_email")):
#         receivers.append(record["parent_email"])
#     if pd.notna(record.get("police_email")):
#         receivers.append(record["police_email"])

#     if not receivers:
#         return

#     body = f"""
# FACE MATCH DETECTED

# Name: {record['child_name']}
# Match Confidence: {match_pct:.2f}%

# Detected At:
# City: {city}
# Region: {region}
# Country: {country}

# Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# """

#     msg = MIMEMultipart()
#     msg["From"] = EMAIL_SENDER
#     msg["To"] = ", ".join(receivers)
#     msg["Subject"] = "🚨 SafeSightNotify Alert"
#     msg.attach(MIMEText(body, "plain"))

#     try:
#         server = smtplib.SMTP("smtp.gmail.com", 587)
#         server.starttls()
#         server.login(EMAIL_SENDER, EMAIL_PASSWORD)
#         server.sendmail(EMAIL_SENDER, receivers, msg.as_string())
#         server.quit()
#         print(f" Alert sent to {receivers}")
#     except Exception as e:
#         print(" Email failed:", e)

# def log_last_seen(record, match_pct):
#     os.makedirs("data/logs", exist_ok=True)
#     pd.DataFrame([{
#         "child_id": record["child_id"],
#         "child_name": record["child_name"],
#         "match_percentage": round(match_pct, 2),
#         "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#         "source": "CAMERA"
#     }]).to_csv(LOG_FILE, mode="a", header=not os.path.exists(LOG_FILE), index=False)

# def match_embedding(query_emb):
#     matches = []
#     for db_emb, record in zip(db_embeddings, db_records):
#         score = 1 - cosine(query_emb, db_emb)
#         if score >= MATCH_THRESHOLD:
#             matches.append((score, record))
#     return sorted(matches, key=lambda x: x[0], reverse=True)

# # ================= LIVE CAMERA =================

# def start_camera():
#     cap = cv2.VideoCapture(CAMERA_INDEX, cv2.CAP_DSHOW)

#     COLORS = [
#         (0, 255, 0), (255, 0, 0), (0, 0, 255),
#         (255, 255, 0), (255, 0, 255), (0, 255, 255)
#     ]

#     def update_frame():
#         ret, frame = cap.read()
#         if not ret:
#             return

#         rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

#         # 🔑 SINGLE PASS FACE DETECTION
#         boxes, probs = mtcnn.detect(rgb)
#         faces = mtcnn(rgb)

#         output_box.delete("1.0", tk.END)

#         if faces is not None and boxes is not None:
#             for i, face in enumerate(faces):
#                 color = COLORS[i % len(COLORS)]

#                 with torch.no_grad():
#                     emb = resnet(face.unsqueeze(0).to(device)).cpu().numpy().flatten()

#                 matches = match_embedding(emb)
#                 if not matches:
#                     continue

#                 #  TOP MATCH
#                 top_score, top_record = matches[0]
#                 child_id = top_record["child_id"]

#                 #  DRAW BOX
#                 x1, y1, x2, y2 = map(int, boxes[i])
#                 cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)

#                 label = f"{top_record['child_name']} ({top_score*100:.1f}%)"
#                 cv2.putText(
#                     frame,
#                     label,
#                     (x1, y1 - 10),
#                     cv2.FONT_HERSHEY_SIMPLEX,
#                     0.6,
#                     color,
#                     2
#                 )

#                 # 🧾 FULL METADATA DISPLAY (RESTORED)
#                 output_box.insert(
#                     tk.END,
#                     f"Name: {top_record['child_name']}\n"
#                     f"Age: {top_record['age']}\n"
#                     f"Gender: {top_record['gender']}\n"
#                     f"City: {top_record['missing_city']}\n"
#                     f"Match: {top_score*100:.2f}%\n"
#                     "-----------------------------\n"
#                 )

#                 # ⏱️ PER-PERSON ALERT COOLDOWN
#                 now = datetime.now()
#                 last_time = last_alert_times.get(child_id)

#                 if last_time is None or (now - last_time).seconds > ALERT_COOLDOWN_SECONDS:
#                     popup_alert(top_record, top_score * 100)
#                     send_email_alert(top_record, top_score * 100)
#                     log_last_seen(top_record, top_score * 100)
#                     last_alert_times[child_id] = now

#         # 🔥 DISPLAY THE MODIFIED FRAME (IMPORTANT)
#         img = ImageTk.PhotoImage(
#             Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)).resize((640, 480))
#         )
#         cam_label.configure(image=img)
#         cam_label.image = img

#         root.after(30, update_frame)

#     update_frame()

# # ================= GUI =================

# root = tk.Tk()
# root.title("SafeSightNotify — Multi-Face Alert System")
# root.geometry("900x800")

# tk.Label(root, text="SafeSightNotify", font=("Arial", 22, "bold")).pack(pady=10)

# cam_label = tk.Label(root)
# cam_label.pack()

# tk.Button(root, text="Start Live Camera", width=30, command=start_camera).pack(pady=10)

# output_box = tk.Text(root, height=12, width=100)
# output_box.pack(pady=10)

# root.mainloop()



# import tkinter as tk
# from tkinter import messagebox
# from PIL import Image, ImageTk
# import cv2
# import numpy as np
# import pandas as pd
# import torch
# from facenet_pytorch import MTCNN, InceptionResnetV1
# from scipy.spatial.distance import cosine
# from datetime import datetime
# import os
# import requests
# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart

# # ================= EMAIL CONFIG =================
# EMAIL_SENDER = "sriyabommakanti@gmail.com"
# EMAIL_PASSWORD = "kyka jddt vqiz nnux"

# # ===============================================

# ALERT_COOLDOWN_SECONDS = 30
# last_alert_time = None

# # ================= SYSTEM CONFIG =================
# META_CSV = "data/cleaned/metadata_private.csv"
# LOG_FILE = "data/logs/last_seen.csv"
# MATCH_THRESHOLD = 0.75
# CAMERA_INDEX = 0
# # ===============================================

# device = "cuda" if torch.cuda.is_available() else "cpu"

# # ================= MODELS =================
# mtcnn = MTCNN(keep_all=False, device=device)
# resnet = InceptionResnetV1(pretrained="vggface2").eval().to(device)

# # ================= LOAD DATABASE =================
# df = pd.read_csv(META_CSV)
# db_embeddings = []
# db_records = []

# for _, row in df.iterrows():
#     if isinstance(row.get("embedding_path"), str):
#         db_embeddings.append(np.load(row["embedding_path"]))
#         db_records.append(row)

# # ================= UTILITIES =================

# def get_current_location():
#     try:
#         r = requests.get("https://ipinfo.io/json", timeout=5)
#         data = r.json()
#         return data.get("city", "Unknown"), data.get("region", "Unknown"), data.get("country", "Unknown")
#     except:
#         return "Unknown", "Unknown", "Unknown"

# def popup_alert(record, match_pct):
#     messagebox.showwarning(
#         "🚨 MATCH FOUND",
#         f"Name: {record['child_name']}\n"
#         f"Match: {match_pct:.2f}%\n"
#         f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
#     )

# def send_email_alert(record, match_pct):
#     city, region, country = get_current_location()

#     subject = "🚨 SafeSightNotify Alert – Face Match Detected"
#     body = f"""
# FACE MATCH DETECTED

# Name: {record['child_name']}
# Match Confidence: {match_pct:.2f}%

# Detected At:
# City: {city}
# Region: {region}
# Country: {country}

# Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# — SafeSightNotify System
# """

#     # 🔑 DYNAMIC RECEIVERS FROM METADATA
#     receivers = []

#     if pd.notna(record.get("parent_email")):
#         receivers.append(record["parent_email"])

#     if pd.notna(record.get("police_email")):
#         receivers.append(record["police_email"])

#     if not receivers:
#         print("⚠️ No valid email receivers found")
#         return

#     msg = MIMEMultipart()
#     msg["From"] = EMAIL_SENDER
#     msg["To"] = ", ".join(receivers)
#     msg["Subject"] = subject
#     msg.attach(MIMEText(body, "plain"))

#     try:
#         server = smtplib.SMTP("smtp.gmail.com", 587)
#         server.starttls()
#         server.login(EMAIL_SENDER, EMAIL_PASSWORD)
#         server.sendmail(EMAIL_SENDER, receivers, msg.as_string())
#         server.quit()
#         print(f"📧 Email sent to {receivers}")
#     except Exception as e:
#         print("❌ Email failed:", e)

# def log_last_seen(record, match_pct):
#     os.makedirs("data/logs", exist_ok=True)
#     row = {
#         "child_id": record["child_id"],
#         "child_name": record["child_name"],
#         "match_percentage": round(match_pct, 2),
#         "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#         "source": "CAMERA"
#     }
#     pd.DataFrame([row]).to_csv(LOG_FILE, mode="a", header=not os.path.exists(LOG_FILE), index=False)

# def match_embedding(query_emb):
#     results = []
#     for db_emb, record in zip(db_embeddings, db_records):
#         score = 1 - cosine(query_emb, db_emb)
#         if score >= MATCH_THRESHOLD:
#             results.append((score, record))
#     results.sort(key=lambda x: x[0], reverse=True)
#     return results

# def format_metadata(record, score):
#     return (
#         f"Name: {record['child_name']}\n"
#         f"Age: {record['age']}\n"
#         f"Gender: {record['gender']}\n"
#         f"City: {record['missing_city']}\n"
#         f"Match: {score*100:.2f}%\n"
#         "-----------------------------\n"
#     )

# # ================= LIVE CAMERA =================

# def start_camera():
#     global last_alert_time
#     cap = cv2.VideoCapture(CAMERA_INDEX, cv2.CAP_DSHOW)

#     def update_frame():
#         global last_alert_time

#         ret, frame = cap.read()
#         if not ret:
#             return

#         rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#         face = mtcnn(rgb)
#         label = "NO MATCH"

#         if face is not None:
#             with torch.no_grad():
#                 emb = resnet(face.unsqueeze(0).to(device)).cpu().numpy().flatten()

#             matches = match_embedding(emb)
#             output_box.delete("1.0", tk.END)

#             if matches:
#                 top_score, top_record = matches[0]

#                 for score, record in matches[:3]:
#                     log_last_seen(record, score * 100)
#                     output_box.insert(tk.END, format_metadata(record, score))

#                 label = f"MATCH ({top_score*100:.1f}%)"

#                 now = datetime.now()
#                 if last_alert_time is None or (now - last_alert_time).seconds > ALERT_COOLDOWN_SECONDS:
#                     popup_alert(top_record, top_score * 100)
#                     send_email_alert(top_record, top_score * 100)
#                     last_alert_time = now

#         cv2.putText(frame, label, (20, 40),
#                     cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

#         img = ImageTk.PhotoImage(Image.fromarray(rgb).resize((300, 250)))
#         cam_label.configure(image=img)
#         cam_label.image = img

#         root.after(30, update_frame)

#     update_frame()

# # ================= GUI =================

# root = tk.Tk()
# root.title("SafeSightNotify — Live Face Alert System")
# root.geometry("800x700")

# tk.Label(root, text="SafeSightNotify", font=("Arial", 22, "bold")).pack(pady=10)

# cam_label = tk.Label(root)
# cam_label.pack()

# tk.Button(root, text="Start Live Camera", width=25, command=start_camera).pack(pady=10)

# output_box = tk.Text(root, height=18, width=90)
# output_box.pack(pady=10)

# root.mainloop()